services:
  frontend:
    build:
      dockerfile:  ./frontend/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3001"
  backend:
    container_name: trade-rush-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/usr/src/app
    stdin_open: true
    tty: true
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      db:
        condition: service_healthy
  db:
    # 本番環境のRDSのmysqlバージョンに合わせたいので、9系はまだ使用しない
    # supported RDS versions: https://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/UserGuide/MySQL.Concepts.VersionMgmt.html#MySQL.Concepts.VersionMgmt.ReleaseCalendar
    # mysql docker images: https://hub.docker.com/_/mysql
    image: mysql:8.4.4
    platform: linux/amd64
    container_name: trade-rush-db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
volumes:
  db-data:
    driver: local
